jdbc.driverLocation=/Users/gaotu/.m2/repository/mysql/mysql-connector-java/8.0.13/mysql-connector-java-8.0.13.jar
jdbc.driverClass=com.mysql.cj.jdbc.Driver
#?????????
jdbc.connectionURL=jdbc:mysql://uqun-test01.mysql.rds.aliyuncs.com:3306/um_individual?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useAffectedRows=true&nullCatalogMeansCurrent=true
jdbc.userId=um_individual_rw
jdbc.password=pkcibhu$yv#dlw5o4n1eqtr7